version: "3.1"

services:

  mongo:
    image: mongo:${MONGO_TAG}
    container_name: "${PROJECT_NAME}_mongo"
    restart: "no"
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    networks:
      - mongo_network

  mongo-express:
    image: mongo-express:latest
    container_name: "${PROJECT_NAME}_mongo_express"
    restart: "no"
    ports:
      - 8081:8081
    depends_on:
      - mongo
    networks:
      - mongo_network

volumes:
  mongo:

networks:
  mongo_network:
